name: curve25519
version: 1.0.0
description:
  Curve25519 Library for cryptographic signing and verifying. Supports VRF signatures and agreements.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  pointycastle:
  collection:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

